name: Deploy production
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"
      - name: Start build notfication
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          disable_web_page_preview: true
          format: html
          message: |
            ⏳ <a href="${{ github.server_url }}/${{ github.repository }}"><b>${{ github.repository }}</b> build started</a>
            ${{ github.workflow }}
            By: ${{ github.actor }}
            Branch: ${{ github.ref }}
            Commit: ${{ github.event.head_commit.message }}
            <a href="${{ github.event.head_commit.url }}">Link</a>

      - name: Install dependencies
        run: |
          yarn install

      - name: Run test
        run: |
          yarn test

      - name: Test Fail
        if: failure()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ${{ github.actor }}
            Test Failed
            Commit : ${{ github.event.commits[0].message }}
            ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}

      - name: Test Success
        if: success()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ${{ github.actor }}
            Test passed
            Commit : ${{ github.event.commits[0].message }}

  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "dcl-metrics-fe"
          heroku_email: "jongwoo.park@code.berlin"

      - name: Finish build notfication
        uses: appleboy/telegram-action@master
        if: always()
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          disable_web_page_preview: true
          format: html
          message: |
            ${{ job.status == 'success' && '✅' || '🆘' }} <a href="${{ github.server_url }}/${{ github.repository }}"><b>${{ github.repository }}</b> build finished</a>
            ${{ github.workflow }}
            By: ${{ github.actor }}
            Branch: ${{ github.ref }}
            Commit: ${{ github.event.head_commit.message }}
            <a href="${{ github.event.head_commit.url }}">Link</a>
