name: Deploy Production
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"
      - name: Start build notfication
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          disable_web_page_preview: true
          format: html
          message: |
            ⏳ <a href="${{ github.repository }}"><b>${{ github.repository }}</b> build started</a>
            ${{ github.workflow }} workflow 
            By: ${{ github.actor }}
            Branch: ${{ github.ref_name }}
            Commit: ${{ github.event.head_commit.message }}
            Commit <a href="${{ github.event.head_commit.url }}">Link</a>

      - name: Install dependencies
        run: |
          yarn install

      - name: Run test
        run: |
          yarn test

      - name: Send Test Fail message
        if: failure()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ❌ Commit <a href="${{ github.event.head_commit.url }}">${{ github.event.head_commit.message }}</a> Test failed..</a>

      - name: Send Test Success message
        if: success()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ✅ Commit <a href="${{ github.event.head_commit.url }}">${{ github.event.head_commit.message }}</a> Test passed!</a>

  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "dcl-metrics-fe"
          heroku_email: "jongwoo.park@code.berlin"

      - name: Finish build notfication
        uses: appleboy/telegram-action@master
        if: always()
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          disable_web_page_preview: true
          format: html
          message: |
            <div>
              <p>${{ github.workflow }} workflow</p>
              <table>
                <tr>
                  ${{ job.status == 'success' && '✅ Build Success!' || '❌ Build Failed..' }} 
                </tr>
                <tr>
                  <td>Repository Link</td>
                  <td>Branch</td>
                  <td>Live Site</td>
                </tr>
                <tr>
                  <td><a href="${{ github.server_url }}/${{ github.repository }}"><b>${{ github.repository }}</b></a></td>
                  <td>${{ github.ref_name }}</td>
                  <td><a href="https://dcl-metrics.com/">dcl-metrics.com</a></td>
                </tr>
              </table>

            </div>
