name: Deploy production
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"
      - name: Install dependencies
        run: |
          yarn install
      - name: Run test
        run: |
          yarn test

      - name: send notification to telegram
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
          Repository: ${{ github.repository }}
          Event name: ${{ github.event.name }}
          Action: ${{ github.action }}
          See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}

  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "dcl-metrics-fe"
          heroku_email: "jongwoo.park@code.berlin"
